version: 2
updates:
  - package-ecosystem: "gomod"
    directory:
      - "client/"
      - "server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories: "server/"
    schedule:
      interval: "daily"