name: Build Client Release Binaries

on:
  release:
    types:
      - created
jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build the executables
        run: cd clients && ./build-executables.sh ${{ github.event.release.tag_name }}

      - name: List the executables
        run: ls -l ./clients/release

      - name: Upload the Rodeo binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./clients/release/chronicle-client-*
          file_glob: true